// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buekdtnguxppyypuyfov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1ZWtkdG5ndXhwcHl5cHV5Zm92Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MTI0MjksImV4cCI6MjA2MDk4ODQyOX0.DdrIv68EXUjxwtjRkEXlFL0epA5boqFSjDoDKcN15tc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);